bitacora_index:
    path:     /
    defaults: { _controller: "SICBundle:Bitacora:index" }
    methods:  GET

bitacora_show:
    path:     /{id}/mostrar
    defaults: { _controller: "SICBundle:Bitacora:show" }
    methods:  GET

bitacora_new:
    path:     /nueva
    defaults: { _controller: "SICBundle:Bitacora:new" }
    methods:  [GET, POST]

bitacora_edit:
    path:     /{id}/editar
    defaults: { _controller: "SICBundle:Bitacora:edit" }
    methods:  [GET, POST]

bitacora_delete:
    path:     /{id}/eliminar
    defaults: { _controller: "SICBundle:Bitacora:delete" }
    methods:  DELETE

bitacora_filtrar:
    path:     /por
    defaults: { _controller: "SICBundle:Bitacora:por" }
    methods:  [POST, DELETE]