comunidades_index:
    path:     /
    defaults: { _controller: "SICBundle:Comunidad:index" }
    methods:  GET

comunidades_show:
    path:     /{id}/show
    defaults: { _controller: "SICBundle:Comunidad:show" }
    methods:  GET

comunidades_new:
    path:     /new
    defaults: { _controller: "SICBundle:Comunidad:new" }
    methods:  [GET, POST]

comunidades_edit:
    path:     /{id}/edit
    defaults: { _controller: "SICBundle:Comunidad:edit" }
    methods:  [GET, POST]

comunidades_delete:
    path:     /{id}/delete
    defaults: { _controller: "SICBundle:Comunidad:delete" }
    methods:  DELETE
