comunidades_index:
    path:     /
    defaults: { _controller: "SICBundle:Comunidad:index" }
    methods:  GET

comunidades_show:
    path:     /{id}/mostrar
    defaults: { _controller: "SICBundle:Comunidad:show" }
    methods:  GET

comunidades_new:
    path:     /nuevo
    defaults: { _controller: "SICBundle:Comunidad:new" }
    methods:  [GET, POST]

comunidades_edit:
    path:     /{id}/editar
    defaults: { _controller: "SICBundle:Comunidad:edit" }
    methods:  [GET, POST]

comunidades_delete:
    path:     /{id}/eliminar
    defaults: { _controller: "SICBundle:Comunidad:delete" }
    methods:  DELETE
