grupofamiliar_index:
    path:     /
    defaults: { _controller: "SICBundle:GrupoFamiliar:index" }
    methods:  GET

grupofamiliar_show:
    path:     /{id}/mostrar
    defaults: { _controller: "SICBundle:GrupoFamiliar:show" }
    methods:  GET

grupofamiliar_new:
    path:     /paso/2/{id_planilla}
    defaults: { _controller: "SICBundle:GrupoFamiliar:new" }
    methods:  [GET, POST]

grupofamiliar_edit:
    path:     /{id}/editar
    defaults: { _controller: "SICBundle:GrupoFamiliar:edit" }
    methods:  [GET, POST]

grupofamiliar_delete:
    path:     /{id}/eliminar
    defaults: { _controller: "SICBundle:GrupoFamiliar:delete" }
    methods:  DELETE
