jefegrupofamiliar_index:
    path:     /
    defaults: { _controller: "SICBundle:JefeGrupoFamiliar:index" }
    methods:  GET

jefegrupofamiliar_show:
    path:     /{id}/show
    defaults: { _controller: "SICBundle:JefeGrupoFamiliar:show" }
    methods:  GET

jefegrupofamiliar_new:
    path:     /paso/1/{id_planilla}
    defaults: { _controller: "SICBundle:JefeGrupoFamiliar:new" }
    methods:  [GET, POST]

jefegrupofamiliar_edit:
    path:     /{id}/edit
    defaults: { _controller: "SICBundle:JefeGrupoFamiliar:edit" }
    methods:  [GET, POST]

jefegrupofamiliar_delete:
    path:     /{id}/delete
    defaults: { _controller: "SICBundle:JefeGrupoFamiliar:delete" }
    methods:  DELETE
