jefegrupofamiliar_index:
    path:     /estadisticas
    defaults: { _controller: "SICBundle:JefeGrupoFamiliar:index" }
    methods:  GET

jefegrupofamiliar_show:
    path:     /{id}/mostrar
    defaults: { _controller: "SICBundle:JefeGrupoFamiliar:show" }
    methods:  GET

jefegrupofamiliar_new:
    path:     /paso/1/{id_planilla}
    defaults: { _controller: "SICBundle:JefeGrupoFamiliar:new" }
    methods:  [GET, POST]

jefegrupofamiliar_edit:
    path:     /{id}/editar
    defaults: { _controller: "SICBundle:JefeGrupoFamiliar:edit" }
    methods:  [GET, POST]

jefegrupofamiliar_delete:
    path:     /{id}/eliminar
    defaults: { _controller: "SICBundle:JefeGrupoFamiliar:delete" }
    methods:  DELETE

resumen_documento_obtener:
    path:     /obtener/documento
    defaults: { _controller: "SICBundle:JefeGrupoFamiliar:obtenerDocumento" }
    methods:  GET

jefegrupofamiliar_vista:
    path:     /vista
    defaults: { _controller: "SICBundle:JefeGrupoFamiliar:vistaDoc" }
    methods:  GET