noticia_index:
    path:     /
    defaults: { _controller: "SICBundle:Noticia:index" }
    methods:  GET

noticia_show:
    path:     /{id}/show
    defaults: { _controller: "SICBundle:Noticia:show" }
    methods:  GET

noticia_new:
    path:     /new
    defaults: { _controller: "SICBundle:Noticia:new" }
    methods:  [GET, POST]

noticia_edit:
    path:     /{id}/edit
    defaults: { _controller: "SICBundle:Noticia:edit" }
    methods:  [GET, POST]

noticia_delete:
    path:     /{id}/delete
    defaults: { _controller: "SICBundle:Noticia:delete" }
    methods:  DELETE

noticia_toggle_visibilidad:
    path:     /{id}/alternar/visibilidad
    defaults: { _controller: "SICBundle:Noticia:alternarVisibilidad" }
    methods:  GET

noticia_newsletter:
    path:     /publicaciones
    defaults: { _controller: "SICBundle:Noticia:newsletter" }
    methods:  GET
