noticia_index:
    path:     /
    defaults: { _controller: "SICBundle:Noticia:index" }
    methods:  GET

noticia_show:
    path:     /{id}/mostrar
    defaults: { _controller: "SICBundle:Noticia:show" }
    methods:  GET

noticia_new:
    path:     /nuevo
    defaults: { _controller: "SICBundle:Noticia:new" }
    methods:  [GET, POST]

noticia_edit:
    path:     /{id}/editar
    defaults: { _controller: "SICBundle:Noticia:edit" }
    methods:  [GET, POST]

noticia_delete:
    path:     /{id}/eliminar
    defaults: { _controller: "SICBundle:Noticia:delete" }
    methods:  DELETE

noticia_toggle_visibilidad:
    path:     /{id}/alternar/visibilidad
    defaults: { _controller: "SICBundle:Noticia:alternarVisibilidad" }
    methods:  GET

noticia_newsletter:
    path:     /publicaciones
    defaults: { _controller: "SICBundle:Noticia:newsletter" }
    methods:  GET

noticia_correo:
    path:     /correos
    defaults: { _controller: "SICBundle:Noticia:correos" }
    methods:  GET

noticia_correo_usuarios:
    path:     /correos/usuarios
    defaults: { _controller: "SICBundle:Noticia:correosUsuarios" }
    methods:  GET

noticia_toggle_correo:
    path:     /{correo}/alternar/subscripcion
    defaults: { _controller: "SICBundle:Noticia:alternarSubscripcion" }
    methods:  GET