noticia_index:
    path:     /
    defaults: { _controller: "SICBundle:Noticia:index" }
    methods:  GET

noticia_show:
    path:     /{id}/mostrar
    defaults: { _controller: "SICBundle:Noticia:show" }
    methods:  GET

noticia_new:
    path:     /nuevo
    defaults: { _controller: "SICBundle:Noticia:new" }
    methods:  [GET, POST]

noticia_edit:
    path:     /{id}/editar
    defaults: { _controller: "SICBundle:Noticia:edit" }
    methods:  [GET, POST]

noticia_delete:
    path:     /{id}/eliminar
    defaults: { _controller: "SICBundle:Noticia:delete" }
    methods:  DELETE

noticia_toggle_visibilidad:
    path:     /{id}/alternar/visibilidad
    defaults: { _controller: "SICBundle:Noticia:alternarVisibilidad" }
    methods:  GET