participacioncomunitaria_index:
    path:     /
    defaults: { _controller: "SICBundle:ParticipacionComunitaria:index" }
    methods:  GET

participacioncomunitaria_show:
    path:     /{id}/show
    defaults: { _controller: "SICBundle:ParticipacionComunitaria:show" }
    methods:  GET

participacioncomunitaria_new:
    path:     /new
    defaults: { _controller: "SICBundle:ParticipacionComunitaria:new" }
    methods:  [GET, POST]

participacioncomunitaria_edit:
    path:     /{id}/edit
    defaults: { _controller: "SICBundle:ParticipacionComunitaria:edit" }
    methods:  [GET, POST]

participacioncomunitaria_delete:
    path:     /{id}/delete
    defaults: { _controller: "SICBundle:ParticipacionComunitaria:delete" }
    methods:  DELETE
