personas_index:
    path:     /estadisticas
    defaults: { _controller: "SICBundle:Persona:index" }
    methods:  GET

personas_show:
    path:     /miembro/{id}/mostrar
    defaults: { _controller: "SICBundle:Persona:show" }
    methods:  GET

personas_new:
    path:     /paso/3/agregar_miembros/{id_planilla}/{id_grupofamiliar}
    defaults: { _controller: "SICBundle:Persona:new" }
    methods:  [GET, POST]

personas_edit:
    path:     /miembro/{id}/editar
    defaults: { _controller: "SICBundle:Persona:edit" }
    methods:  [GET, POST]

personas_delete:
    path:     /miembro/{id}/eliminar
    defaults: { _controller: "SICBundle:Persona:delete" }
    methods:  DELETE

agenda_comunitaria:
    path:     /agenda/comunitaria
    defaults: { _controller: "SICBundle:Persona:agenda" }
    methods:  GET

personas_nuevo_miembro:
    path:     /nuevo/{id_planilla}/{id_grupofamiliar}
    defaults: { _controller: "SICBundle:Persona:nuevoMiembro" }
    methods:  [GET, POST]