personas_index:
    path:     /estadisticas
    defaults: { _controller: "SICBundle:Persona:index" }
    methods:  GET

personas_show:
    path:     /{id}/show
    defaults: { _controller: "SICBundle:Persona:show" }
    methods:  GET

personas_new:
    path:     /paso/3/agregar_miembros/{id_planilla}/{id_grupofamiliar}
    defaults: { _controller: "SICBundle:Persona:new" }
    methods:  [GET, POST]

personas_edit:
    path:     /{id}/edit
    defaults: { _controller: "SICBundle:Persona:edit" }
    methods:  [GET, POST]

personas_delete:
    path:     /{id}/delete
    defaults: { _controller: "SICBundle:Persona:delete" }
    methods:  DELETE

agenda_comunitaria:
    path:     /agenda/comunitaria
    defaults: { _controller: "SICBundle:Persona:agenda" }
    methods:  GET

agenda_comunitaria_personas:
    path:     /agenda/comunitaria/personas
    defaults: { _controller: "SICBundle:Persona:getDatatable" }
    methods:  GET

personas_nuevo_miembro:
    path:     /nuevo/{id_planilla}/{id_grupofamiliar}
    defaults: { _controller: "SICBundle:Persona:nuevoMiembro" }
    methods:  [GET, POST]