planillas_index:
    path:     /
    defaults: { _controller: "SICBundle:Planillas:index" }
    methods:  GET

planillas_show:
    path:     /{id}/mostrar
    defaults: { _controller: "SICBundle:Planillas:show" }
    methods:  GET

planillas_new:
    path:     /nuevo
    defaults: { _controller: "SICBundle:Planillas:new" }
    methods:  [GET, POST]

planillas_edit:
    path:     /{id}/editar
    defaults: { _controller: "SICBundle:Planillas:edit" }
    methods:  [GET, POST]

planillas_delete:
    path:     /{id}/eliminar
    defaults: { _controller: "SICBundle:Planillas:delete" }
    methods:  DELETE

planillas_continuar_encuesta:
    path:     /{id_encuesta}/continuar
    defaults: { _controller: "SICBundle:Planillas:conitnuarEncuesta" }
    methods:  [GET, POST]

planillas_observacion_carga:
    path:     /{id_planilla}/observacion/cargar
    defaults: { _controller: "SICBundle:Planillas:cargarObservacion" }
    methods:  [GET, POST]

new_element_ajax:
    path:     /nuevo/agregar/ajax
    defaults: { _controller: "SICBundle:Planillas:new_element_ajax" }
    methods:  [GET, POST]

planillas_imprimir:
    path:     /{id}/imprimir
    defaults: { _controller: "SICBundle:Planillas:imprimir" }
    methods:  GET