sic_homepage:
    path:     /
    defaults: { _controller: "SICBundle:Inicio:inicio" }
    methods:  GET

sic_homepage_login:
    path:     /login
    defaults: { _controller: "SICBundle:Inicio:login" }
    methods:  GET

sic_administacion_entidades:
    path:     /administrar/datos/cc
    defaults: { _controller: "SICBundle:Inicio:administrarEntidades"}
    methods:  GET

sic_administacion_parametros_planilla:
    path:     /administrar/parametros/planilla
    defaults: { _controller: "SICBundle:Inicio:administrarParametros"}
    methods:  GET

sic_volver_parametros:
    path:     /administrar/parametros/{index}
    defaults: { _controller: "SICBundle:Inicio:volverParametros"}
    methods:  GET

sic_documentos_cuaderno_votacion:
    path:     /documentos/cuaderno-votacion
    defaults: { _controller: "SICBundle:Inicio:cuadernoVotacion"}
    methods:  GET

sic_documentos_cuaderno_votacion_pdf:
    path:     /documentos/cuaderno-votacion/pdf
    defaults: { _controller: "SICBundle:Inicio:cuadernoVotacionPDF"}
    methods:  GET

sic_documentos_resumen_censo:
    path:     /documentos/resumen-censo
    defaults: { _controller: "SICBundle:Inicio:resumenCenso"}
    methods:  GET

sic_documentos_resumen_censo_pdf:
    path:     /documentos/resumen-censo/pdf
    defaults: { _controller: "SICBundle:Inicio:resumenCensoPDF"}
    methods:  GET

sic_documentos_registro_electoral:
    path:     /documentos/registro-electoral
    defaults: { _controller: "SICBundle:Inicio:registroElectoral"}
    methods:  GET

sic_documentos_registro_electoral_pdf:
    path:     /documentos/registro-electoral/pdf
    defaults: { _controller: "SICBundle:Inicio:registroElectoralPDF"}
    methods:  GET

sic_documentos_registro_preliminar:
    path:     /documentos/registro-preliminar
    defaults: { _controller: "SICBundle:Inicio:registroPreliminar"}
    methods:  GET

sic_documentos_registro_preliminar_pdf:
    path:     /documentos/registro-preliminar-pdf
    defaults: { _controller: "SICBundle:Inicio:registroPreliminarPDF"}
    methods:  GET

sic_buscador_inicio:
    path:     /sic_buscador_inicio
    defaults: { _controller: "SICBundle:Inicio:buscador" }
    methods:  POST

sic_test_excel:
    path:     /documento/excel
    defaults: { _controller: "SICBundle:Excel:index"}
    methods:  GET

sic_todas_las_planillas:
    path:     /documento/obtener/todas/las/planillas
    defaults: { _controller: "SICBundle:Planillas:obtenerTodas"}
    methods:  GET

noticia_correo:
    path:     /correos
    defaults: { _controller: "SICBundle:Noticia:correos" }
    methods:  GET

noticia_correo_usuarios:
    path:     /correos/usuarios
    defaults: { _controller: "SICBundle:Noticia:correosUsuarios" }
    methods:  GET

noticia_toggle_correo:
    path:     /{correo}/alternar/subscripcion
    defaults: { _controller: "SICBundle:Noticia:alternarSubscripcion" }
    methods:  GET

ayuda_del_sistema:
    path:     /ayuda
    defaults: { _controller: "SICBundle:Inicio:ayudaSistema" }
    methods:  GET

descargar_manual:
    path:     /ayuda/descargar-manual/{tipo_manual}
    defaults: { _controller: "SICBundle:Inicio:descargarManual" }
    methods:  GET

# RUTAS PARA LA PARTE PUBLICA DEL SISTEMA
# Noticias del Consejo Comunal
noticia_newsletter:
    path:     /publico/noticias
    defaults: { _controller: "SICBundle:Noticia:newsletter" }
    methods:  GET

publico_vocerias:
    path:     /publico/vocerias
    defaults: { _controller: "SICBundle:Noticia:vocerias" }
    methods:  GET