sic_homepage:
    path:     /
    defaults: { _controller: "SICBundle:Inicio:inicio" }
    methods:  GET

sic_homepage:
    path:     /login
    defaults: { _controller: "SICBundle:Inicio:login" }
    methods:  GET

sic_administacion_entidades:
    path:     /administrar/parametros/entidades
    defaults: { _controller: "SICBundle:Inicio:administrarEntidades"}
    methods:  GET