fos_user_security_login:
    path:     /iniciar-sesion
    methods:  GET POST
    defaults: { _controller: "FOSUserBundle:Security:login" }

fos_user_security_check:
    path:     /login_check
    methods:  POST
    defaults: { _controller: "FOSUserBundle:Security:check" }

fos_user_security_logout:
    path:     /cerrar-sesion
    methods:  GET
    defaults: { _controller: "FOSUserBundle:Security:logout" }