situacionsalud_index:
    path:     /estadisticas
    defaults: { _controller: "SICBundle:SituacionSalud:index" }
    methods:  GET

situacionsalud_show:
    path:     /{id}/mostrar
    defaults: { _controller: "SICBundle:SituacionSalud:show" }
    methods:  GET

situacionsalud_new:
    path:     /paso/6/{id_planilla}/
    defaults: { _controller: "SICBundle:SituacionSalud:new" }
    methods:  [GET, POST]

situacionsalud_edit:
    path:     /{id}/editar
    defaults: { _controller: "SICBundle:SituacionSalud:edit" }
    methods:  [GET, POST]

situacionsalud_delete:
    path:     /{id}/eliminar
    defaults: { _controller: "SICBundle:SituacionSalud:delete" }
    methods:  DELETE
