situacionvivienda_index:
    path:     /estadisticas
    defaults: { _controller: "SICBundle:SituacionVivienda:index" }
    methods:  GET

situacionvivienda_show:
    path:     /{id}/mostrar
    defaults: { _controller: "SICBundle:SituacionVivienda:show" }
    methods:  GET

situacionvivienda_new:
    path:     /paso/5/{id_planilla}/
    defaults: { _controller: "SICBundle:SituacionVivienda:new" }
    methods:  [GET, POST]

situacionvivienda_edit:
    path:     /{id}/editar
    defaults: { _controller: "SICBundle:SituacionVivienda:edit" }
    methods:  [GET, POST]

situacionvivienda_delete:
    path:     /{id}/eliminar
    defaults: { _controller: "SICBundle:SituacionVivienda:delete" }
    methods:  DELETE
