situacioncomunidad_index:
    path:     /
    defaults: { _controller: "SICBundle:SituacionComunidad:index" }
    methods:  GET

situacioncomunidad_show:
    path:     /{id}/show
    defaults: { _controller: "SICBundle:SituacionComunidad:show" }
    methods:  GET

situacioncomunidad_new:
    path:     /paso/9/{id_planilla}/
    defaults: { _controller: "SICBundle:SituacionComunidad:new" }
    methods:  [GET, POST]

situacioncomunidad_edit:
    path:     /{id}/edit
    defaults: { _controller: "SICBundle:SituacionComunidad:edit" }
    methods:  [GET, POST]

situacioncomunidad_delete:
    path:     /{id}/delete
    defaults: { _controller: "SICBundle:SituacionComunidad:delete" }
    methods:  DELETE
