situacionservicios_index:
    path:     /estadisticas
    defaults: { _controller: "SICBundle:SituacionServicios:index" }
    methods:  GET

situacionservicios_show:
    path:     /{id}/show
    defaults: { _controller: "SICBundle:SituacionServicios:show" }
    methods:  GET

situacionservicios_new:
    path:     /paso/7/{id_planilla}/
    defaults: { _controller: "SICBundle:SituacionServicios:new" }
    methods:  [GET, POST]

situacionservicios_edit:
    path:     /{id}/edit
    defaults: { _controller: "SICBundle:SituacionServicios:edit" }
    methods:  [GET, POST]

situacionservicios_delete:
    path:     /{id}/delete
    defaults: { _controller: "SICBundle:SituacionServicios:delete" }
    methods:  DELETE
