usuarios_index:
    path:     /
    defaults: { _controller: "SICBundle:Usuario:index" }
    methods:  GET

usuarios_show:
    path:     /{id}/mostrar
    defaults: { _controller: "SICBundle:Usuario:show" }
    methods:  GET

usuarios_new:
    path:     /nuevo
    defaults: { _controller: "SICBundle:Usuario:new" }
    methods:  [GET, POST]

usuarios_edit:
    path:     /{id}/editarar
    defaults: { _controller: "SICBundle:Usuario:edit" }
    methods:  [GET, POST]

usuarios_delete:
    path:     /{id}/eliminar
    defaults: { _controller: "SICBundle:Usuario:delete" }
    methods:  DELETE
