vocero_index:
    path:     /
    defaults: { _controller: "SICBundle:Vocero:index" }
    methods:  GET

vocero_show:
    path:     /{id}/show
    defaults: { _controller: "SICBundle:Vocero:show" }
    methods:  GET

vocero_new:
    path:     /new
    defaults: { _controller: "SICBundle:Vocero:new" }
    methods:  [GET, POST]

vocero_edit:
    path:     /{id}/edit
    defaults: { _controller: "SICBundle:Vocero:edit" }
    methods:  [GET, POST]

vocero_delete:
    path:     /{id}/delete
    defaults: { _controller: "SICBundle:Vocero:delete" }
    methods:  DELETE
