imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [!event]
        console:
            type:   console
            bubble: false
            channels: [!event, !doctrine]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

swiftmailer:
    transport:  smtp
    encryption: ssl
    auth_mode:  login
    host:       server32.hostwhitelabel.com
    port:       465
    username:   gpscaracas@registro1991.com.ve
    password:   gpscaracas2016
    delivery_address: 'mainstr3ammusic@gmail.com' #Direccion para enviar mensajes mientras estoy en desarrollo

