sic_admin_preguntas_sit_com:
    resource: "@SICBundle/Controller/AdminPreguntasSitComController.php"
    type:     annotation

sic:
    resource: "@SICBundle/Resources/config/routing.yml"

fos_user:
    resource: "@SICBundle/Resources/config/routing/FOSUserBundle/all.xml"