<?php

namespace SICBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdminRecoleccionBasuraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminRecoleccionBasuraRepository extends EntityRepository
{
}
