<?php

namespace SICBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdminEstadoCivilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminEstadoCivilRepository extends EntityRepository
{
}
