<?php

namespace SICBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdminClasIngresoFamiliarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminClasIngresoFamiliarRepository extends EntityRepository
{
}
