<?php

namespace SICBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdminTipoMascotasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminTipoMascotasRepository extends EntityRepository
{
}
