<?php

namespace SICBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BitacoraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BitacoraRepository extends EntityRepository
{
    public function findRango($ini, $fin, $criteria)
    {
        if ($criteria != 'todos') {   
            $query = $this->getEntityManager()
                    ->createQuery('SELECT u 
                    FROM SICBundle:Bitacora u
                    WHERE u.fecha >= :inicio AND u.fecha <= :fin AND u.accion = :criteria
                    ORDER BY u.fecha DESC');
            $query->setparameter('inicio', $ini);
            $query->setparameter('fin', $fin);
            $query->setparameter('criteria', $criteria);
        }else{
            $query = $this->getEntityManager()
                    ->createQuery('SELECT u 
                    FROM SICBundle:Bitacora u
                    WHERE u.fecha >= :inicio AND u.fecha <= :fin
                    ORDER BY u.fecha DESC');
            $query->setparameter('inicio', $ini);
            $query->setparameter('fin', $fin);
        }

        return $query->getResult();
    }
}
