<?php

namespace SICBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ComunicadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComunicadoRepository extends EntityRepository
{
	/*Devuelve a todos las personas que tiene correo y tiene activa la opción de recibir correos*/
	public function PersonasCorreo()
	{
		$query = $this->getEntityManager()
            ->createQuery(
			'SELECT p
			FROM SICBundle:Persona p
			WHERE p.email != :var
				AND p.recibir_correo = :var2'
		)
            ->setParameter('var', '')
            ->setParameter('var2', '1');

		$personas = $query->getResult();

		$todos = array();
		foreach ($personas as $p) {
			array_push($todos, $p);
		}

		$query = $this->getEntityManager()
            ->createQuery(
			'SELECT p
			FROM SICBundle:JefeGrupoFamiliar p
			WHERE p.email != :var
				AND p.recibir_correo = :var2'
		)
            ->setParameter('var', '')
            ->setParameter('var2', '1');

		$personas = $query->getResult();

		foreach ($personas as $p) {
			array_push($todos, $p);
		}

		return $todos;
	}
}
