<?php

namespace SICBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GrupoFamiliarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrupoFamiliarRepository extends EntityRepository
{
	public function findSectores()
	{
		$query = $this->getEntityManager()
                ->createQuery('SELECT gf 
                FROM SICBundle:GrupoFamiliar gf
                GROUP BY gf.sector');
        $result = $query->getResult();
        return $result;
	}
}
