<?php

namespace SICBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * JefeGrupoFamiliarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JefeGrupoFamiliarRepository extends EntityRepository
{
	public function mayores_de($edad)
	{
		$query = $this->getEntityManager()
                ->createQuery('SELECT u 
                FROM SICBundle:JefeGrupoFamiliar u
                WHERE
                    u.edad >= :edad
                ORDER BY
                	u.cedula ASC');
        
        $query->setparameter('edad', $edad);
        $result = $query->getResult();
        return $result;
	}
}
