<?php

namespace SICBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NoticiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoticiaRepository extends EntityRepository
{
	/* retorna la cantidad de personas con correo que está recibiendo mensajes
	no inlcuye miembro del consejo comunal (entidad usuarios) */
	public function CantidadPersonasCorreo()
	{
		$query = $this->getEntityManager()
            ->createQuery(
			'SELECT COUNT(p)
			FROM SICBundle:Persona p
			WHERE p.email != :var
				AND p.recibir_correo = :var2'
		)
            ->setParameter('var', '')
            ->setParameter('var2', '1');

		$cant = $query->getSingleScalarResult();

		$query = $this->getEntityManager()
            ->createQuery(
			'SELECT COUNT(p)
			FROM SICBundle:JefeGrupoFamiliar p
			WHERE p.email != :var
				AND p.recibir_correo = :var2'
		)
            ->setParameter('var', '')
            ->setParameter('var2', '1');

		$cant = $query->getSingleScalarResult() + $cant;
		
		return $cant;
	}

	/* Obtiene las últimas 5 noticias en orden descendiente y que están visibles */
	public function NoticiasOrdenDesc()
	{
		$query = $this->getEntityManager()
            ->createQuery(
			'SELECT n
			FROM SICBundle:Noticia n
			WHERE n.visibilidad = :var
				ORDER BY n.fechaPub DESC'
		)
            ->setParameter('var', '1');

		$result = $query->setMaxResults(5)->getResult();
		return $result;
	}
}
