<?php

namespace SICBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SituacionEconomicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SituacionEconomicaRepository extends EntityRepository
{
	public function findByActividadComercialVivienda($situacion )
    {
         return $this->getEntityManager()
                ->createQueryBuilder()
                ->select('m')
                ->from('SICBundle:SituacionEconomica', 'm')
                ->innerJoin('m.actividadComercialenVivienda', 'e')
                ->where('e.id = :exampleid' )
                ->setParameter('exampleid', $situacion->getId() )
                ->getQuery()
                ->getResult();
    }
}
