<?php

namespace SICBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SituacionSaludRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SituacionSaludRepository extends EntityRepository
{
	public function padecencia($situacion)
    {
         return $this->getEntityManager()
                ->createQueryBuilder()
                ->select('m')
                ->from('SICBundle:SituacionSalud', 'm')
                ->innerJoin('m.padecencia', 'e')
                ->where('e.id = :exampleid' )
                ->setParameter('exampleid', $situacion->getId() )
                ->getQuery()
                ->getResult();
    }

    public function ayudaEspecial($situacion)
    {
         return $this->getEntityManager()
                ->createQueryBuilder()
                ->select('m')
                ->from('SICBundle:SituacionSalud', 'm')
                ->innerJoin('m.ayudaEspecial', 'e')
                ->where('e.id = :exampleid' )
                ->setParameter('exampleid', $situacion->getId() )
                ->getQuery()
                ->getResult();
    }

    public function situacionExclusion()
    {
        $query = $this->getEntityManager()
                ->createQuery('SELECT x.situacion, SUM(x.cantidad) as cantidad
                    FROM SICBundle:AdminTipoSituacionExclusion x
                    GROUP BY x.situacion
                ');
        $result = $query->getResult();
        return $result;
    }
}
