configurable_tipo_enseres_index:
    path:     /
    defaults: { _controller: "SICBundle:AdminTipoEnseres:index" }
    methods:  GET

configurable_tipo_enseres_show:
    path:     /{id}/show
    defaults: { _controller: "SICBundle:AdminTipoEnseres:show" }
    methods:  GET

configurable_tipo_enseres_new:
    path:     /new
    defaults: { _controller: "SICBundle:AdminTipoEnseres:new" }
    methods:  [GET, POST]

configurable_tipo_enseres_edit:
    path:     /{id}/edit
    defaults: { _controller: "SICBundle:AdminTipoEnseres:edit" }
    methods:  [GET, POST]

configurable_tipo_enseres_delete:
    path:     /{id}/delete
    defaults: { _controller: "SICBundle:AdminTipoEnseres:delete" }
    methods:  DELETE
