configurable_respuesta_cerrada_index:
    path:     /
    defaults: { _controller: "SICBundle:AdminRespCerrada:index" }
    methods:  GET

configurable_respuesta_cerrada_show:
    path:     /{id}/show
    defaults: { _controller: "SICBundle:AdminRespCerrada:show" }
    methods:  GET

configurable_respuesta_cerrada_new:
    path:     /new
    defaults: { _controller: "SICBundle:AdminRespCerrada:new" }
    methods:  [GET, POST]

configurable_respuesta_cerrada_edit:
    path:     /{id}/edit
    defaults: { _controller: "SICBundle:AdminRespCerrada:edit" }
    methods:  [GET, POST]

configurable_respuesta_cerrada_delete:
    path:     /{id}/delete
    defaults: { _controller: "SICBundle:AdminRespCerrada:delete" }
    methods:  DELETE
