configurables_tipos_misiones_comunidad_index:
    path:     /
    defaults: { _controller: "SICBundle:AdminMisionesComunidad:index" }
    methods:  GET

configurables_tipos_misiones_comunidad_show:
    path:     /{id}/show
    defaults: { _controller: "SICBundle:AdminMisionesComunidad:show" }
    methods:  GET

configurables_tipos_misiones_comunidad_new:
    path:     /new
    defaults: { _controller: "SICBundle:AdminMisionesComunidad:new" }
    methods:  [GET, POST]

configurables_tipos_misiones_comunidad_edit:
    path:     /{id}/edit
    defaults: { _controller: "SICBundle:AdminMisionesComunidad:edit" }
    methods:  [GET, POST]

configurables_tipos_misiones_comunidad_delete:
    path:     /{id}/delete
    defaults: { _controller: "SICBundle:AdminMisionesComunidad:delete" }
    methods:  DELETE
