configurables_preguntas_index:
    path:     /
    defaults: { _controller: "SICBundle:AdminPreguntas:index" }
    methods:  GET

configurables_preguntas_show:
    path:     /{id}/show
    defaults: { _controller: "SICBundle:AdminPreguntas:show" }
    methods:  GET

configurables_preguntas_new:
    path:     /new
    defaults: { _controller: "SICBundle:AdminPreguntas:new" }
    methods:  [GET, POST]

configurables_preguntas_edit:
    path:     /{id}/edit
    defaults: { _controller: "SICBundle:AdminPreguntas:edit" }
    methods:  [GET, POST]

configurables_preguntas_delete:
    path:     /{id}/delete
    defaults: { _controller: "SICBundle:AdminPreguntas:delete" }
    methods:  DELETE
