adminpreguntassitcom_index:
    path:     /
    defaults: { _controller: "SICBundle:AdminPreguntasSitCom:index" }
    methods:  GET

adminpreguntassitcom_show:
    path:     /{id}/show
    defaults: { _controller: "SICBundle:AdminPreguntasSitCom:show" }
    methods:  GET

adminpreguntassitcom_new:
    path:     /new
    defaults: { _controller: "SICBundle:AdminPreguntasSitCom:new" }
    methods:  [GET, POST]

adminpreguntassitcom_edit:
    path:     /{id}/edit
    defaults: { _controller: "SICBundle:AdminPreguntasSitCom:edit" }
    methods:  [GET, POST]

adminpreguntassitcom_delete:
    path:     /{id}/delete
    defaults: { _controller: "SICBundle:AdminPreguntasSitCom:delete" }
    methods:  DELETE
