configurable_estado_civil_index:
    path:     /
    defaults: { _controller: "SICBundle:AdminEstadoCivil:index" }
    methods:  GET

configurable_estado_civil_show:
    path:     /{id}/show
    defaults: { _controller: "SICBundle:AdminEstadoCivil:show" }
    methods:  GET

configurable_estado_civil_new:
    path:     /new
    defaults: { _controller: "SICBundle:AdminEstadoCivil:new" }
    methods:  [GET, POST]

configurable_estado_civil_edit:
    path:     /{id}/edit
    defaults: { _controller: "SICBundle:AdminEstadoCivil:edit" }
    methods:  [GET, POST]

configurable_estado_civil_delete:
    path:     /{id}/delete
    defaults: { _controller: "SICBundle:AdminEstadoCivil:delete" }
    methods:  DELETE
