configurable_tipo_ayuda_especial_index:
    path:     /
    defaults: { _controller: "SICBundle:AdminTipoAyudaEspecial:index" }
    methods:  GET

configurable_tipo_ayuda_especial_show:
    path:     /{id}/show
    defaults: { _controller: "SICBundle:AdminTipoAyudaEspecial:show" }
    methods:  GET

configurable_tipo_ayuda_especial_new:
    path:     /new
    defaults: { _controller: "SICBundle:AdminTipoAyudaEspecial:new" }
    methods:  [GET, POST]

configurable_tipo_ayuda_especial_edit:
    path:     /{id}/edit
    defaults: { _controller: "SICBundle:AdminTipoAyudaEspecial:edit" }
    methods:  [GET, POST]

configurable_tipo_ayuda_especial_delete:
    path:     /{id}/delete
    defaults: { _controller: "SICBundle:AdminTipoAyudaEspecial:delete" }
    methods:  DELETE
