admincapacidadbombona_index:
    path:     /
    defaults: { _controller: "SICBundle:AdminCapacidadBombona:index" }
    methods:  GET

admincapacidadbombona_show:
    path:     /{id}/show
    defaults: { _controller: "SICBundle:AdminCapacidadBombona:show" }
    methods:  GET

admincapacidadbombona_new:
    path:     /new
    defaults: { _controller: "SICBundle:AdminCapacidadBombona:new" }
    methods:  [GET, POST]

admincapacidadbombona_edit:
    path:     /{id}/edit
    defaults: { _controller: "SICBundle:AdminCapacidadBombona:edit" }
    methods:  [GET, POST]

admincapacidadbombona_delete:
    path:     /{id}/delete
    defaults: { _controller: "SICBundle:AdminCapacidadBombona:delete" }
    methods:  DELETE
