configurables_tipos_gas_index:
    path:     /
    defaults: { _controller: "SICBundle:AdminTipoGas:index" }
    methods:  GET

configurables_tipos_gas_show:
    path:     /{id}/show
    defaults: { _controller: "SICBundle:AdminTipoGas:show" }
    methods:  GET

configurables_tipos_gas_new:
    path:     /new
    defaults: { _controller: "SICBundle:AdminTipoGas:new" }
    methods:  [GET, POST]

configurables_tipos_gas_edit:
    path:     /{id}/edit
    defaults: { _controller: "SICBundle:AdminTipoGas:edit" }
    methods:  [GET, POST]

configurables_tipos_gas_delete:
    path:     /{id}/delete
    defaults: { _controller: "SICBundle:AdminTipoGas:delete" }
    methods:  DELETE
