configurables_tipo_sistema_electrico_index:
    path:     /
    defaults: { _controller: "SICBundle:AdminSistemaElectrico:index" }
    methods:  GET

configurables_tipo_sistema_electrico_show:
    path:     /{id}/show
    defaults: { _controller: "SICBundle:AdminSistemaElectrico:show" }
    methods:  GET

configurables_tipo_sistema_electrico_new:
    path:     /new
    defaults: { _controller: "SICBundle:AdminSistemaElectrico:new" }
    methods:  [GET, POST]

configurables_tipo_sistema_electrico_edit:
    path:     /{id}/edit
    defaults: { _controller: "SICBundle:AdminSistemaElectrico:edit" }
    methods:  [GET, POST]

configurables_tipo_sistema_electrico_delete:
    path:     /{id}/delete
    defaults: { _controller: "SICBundle:AdminSistemaElectrico:delete" }
    methods:  DELETE
