configurable_tipo_habitaciones_index:
    path:     /
    defaults: { _controller: "SICBundle:AdminTipoHabitacionesVivienda:index" }
    methods:  GET

configurable_tipo_habitaciones_show:
    path:     /{id}/show
    defaults: { _controller: "SICBundle:AdminTipoHabitacionesVivienda:show" }
    methods:  GET

configurable_tipo_habitaciones_new:
    path:     /new
    defaults: { _controller: "SICBundle:AdminTipoHabitacionesVivienda:new" }
    methods:  [GET, POST]

configurable_tipo_habitaciones_edit:
    path:     /{id}/edit
    defaults: { _controller: "SICBundle:AdminTipoHabitacionesVivienda:edit" }
    methods:  [GET, POST]

configurable_tipo_habitaciones_delete:
    path:     /{id}/delete
    defaults: { _controller: "SICBundle:AdminTipoHabitacionesVivienda:delete" }
    methods:  DELETE
