configurable_incapacidades_index:
    path:     /
    defaults: { _controller: "SICBundle:AdminIncapacidades:index" }
    methods:  GET

configurable_incapacidades_show:
    path:     /{id}/show
    defaults: { _controller: "SICBundle:AdminIncapacidades:show" }
    methods:  GET

configurable_incapacidades_new:
    path:     /new
    defaults: { _controller: "SICBundle:AdminIncapacidades:new" }
    methods:  [GET, POST]

configurable_incapacidades_edit:
    path:     /{id}/edit
    defaults: { _controller: "SICBundle:AdminIncapacidades:edit" }
    methods:  [GET, POST]

configurable_incapacidades_delete:
    path:     /{id}/delete
    defaults: { _controller: "SICBundle:AdminIncapacidades:delete" }
    methods:  DELETE
