configurable_tipo_tenencia_index:
    path:     /
    defaults: { _controller: "SICBundle:AdminTipoTenencia:index" }
    methods:  GET

configurable_tipo_tenencia_show:
    path:     /{id}/show
    defaults: { _controller: "SICBundle:AdminTipoTenencia:show" }
    methods:  GET

configurable_tipo_tenencia_new:
    path:     /new
    defaults: { _controller: "SICBundle:AdminTipoTenencia:new" }
    methods:  [GET, POST]

configurable_tipo_tenencia_edit:
    path:     /{id}/edit
    defaults: { _controller: "SICBundle:AdminTipoTenencia:edit" }
    methods:  [GET, POST]

configurable_tipo_tenencia_delete:
    path:     /{id}/delete
    defaults: { _controller: "SICBundle:AdminTipoTenencia:delete" }
    methods:  DELETE
