configurable_ubicacion-trabajo_index:
    path:     /
    defaults: { _controller: "SICBundle:AdminUbicacionTrabajo:index" }
    methods:  GET

configurable_ubicacion-trabajo_show:
    path:     /{id}/show
    defaults: { _controller: "SICBundle:AdminUbicacionTrabajo:show" }
    methods:  GET

configurable_ubicacion-trabajo_new:
    path:     /new
    defaults: { _controller: "SICBundle:AdminUbicacionTrabajo:new" }
    methods:  [GET, POST]

configurable_ubicacion-trabajo_edit:
    path:     /{id}/edit
    defaults: { _controller: "SICBundle:AdminUbicacionTrabajo:edit" }
    methods:  [GET, POST]

configurable_ubicacion-trabajo_delete:
    path:     /{id}/delete
    defaults: { _controller: "SICBundle:AdminUbicacionTrabajo:delete" }
    methods:  DELETE
