configurables_tipo_recoleccion_basura_index:
    path:     /
    defaults: { _controller: "SICBundle:AdminRecoleccionBasura:index" }
    methods:  GET

configurables_tipo_recoleccion_basura_show:
    path:     /{id}/show
    defaults: { _controller: "SICBundle:AdminRecoleccionBasura:show" }
    methods:  GET

configurables_tipo_recoleccion_basura_new:
    path:     /new
    defaults: { _controller: "SICBundle:AdminRecoleccionBasura:new" }
    methods:  [GET, POST]

configurables_tipo_recoleccion_basura_edit:
    path:     /{id}/edit
    defaults: { _controller: "SICBundle:AdminRecoleccionBasura:edit" }
    methods:  [GET, POST]

configurables_tipo_recoleccion_basura_delete:
    path:     /{id}/delete
    defaults: { _controller: "SICBundle:AdminRecoleccionBasura:delete" }
    methods:  DELETE
