configurable_tipo_situacion_exclusion_index:
    path:     /
    defaults: { _controller: "SICBundle:AdminTipoSituacionExclusion:index" }
    methods:  GET

configurable_tipo_situacion_exclusion_show:
    path:     /{id}/show
    defaults: { _controller: "SICBundle:AdminTipoSituacionExclusion:show" }
    methods:  GET

configurable_tipo_situacion_exclusion_new:
    path:     /new
    defaults: { _controller: "SICBundle:AdminTipoSituacionExclusion:new" }
    methods:  [GET, POST]

configurable_tipo_situacion_exclusion_edit:
    path:     /{id}/edit
    defaults: { _controller: "SICBundle:AdminTipoSituacionExclusion:edit" }
    methods:  [GET, POST]

configurable_tipo_situacion_exclusion_delete:
    path:     /{id}/delete
    defaults: { _controller: "SICBundle:AdminTipoSituacionExclusion:delete" }
    methods:  DELETE
