configurable_nivel_instruccion_index:
    path:     /
    defaults: { _controller: "SICBundle:AdminNivelInstruccion:index" }
    methods:  GET

configurable_nivel_instruccion_show:
    path:     /{id}/show
    defaults: { _controller: "SICBundle:AdminNivelInstruccion:show" }
    methods:  GET

configurable_nivel_instruccion_new:
    path:     /new
    defaults: { _controller: "SICBundle:AdminNivelInstruccion:new" }
    methods:  [GET, POST]

configurable_nivel_instruccion_edit:
    path:     /{id}/edit
    defaults: { _controller: "SICBundle:AdminNivelInstruccion:edit" }
    methods:  [GET, POST]

configurable_nivel_instruccion_delete:
    path:     /{id}/delete
    defaults: { _controller: "SICBundle:AdminNivelInstruccion:delete" }
    methods:  DELETE
