configurable_tipo_mascotas_index:
    path:     /
    defaults: { _controller: "SICBundle:AdminTipoMascotas:index" }
    methods:  GET

configurable_tipo_mascotas_show:
    path:     /{id}/show
    defaults: { _controller: "SICBundle:AdminTipoMascotas:show" }
    methods:  GET

configurable_tipo_mascotas_new:
    path:     /new
    defaults: { _controller: "SICBundle:AdminTipoMascotas:new" }
    methods:  [GET, POST]

configurable_tipo_mascotas_edit:
    path:     /{id}/edit
    defaults: { _controller: "SICBundle:AdminTipoMascotas:edit" }
    methods:  [GET, POST]

configurable_tipo_mascotas_delete:
    path:     /{id}/delete
    defaults: { _controller: "SICBundle:AdminTipoMascotas:delete" }
    methods:  DELETE
