configurables_tipos_aguas_blancas_index:
    path:     /
    defaults: { _controller: "SICBundle:AdminAguasBlancas:index" }
    methods:  GET

configurables_tipos_aguas_blancas_show:
    path:     /{id}/show
    defaults: { _controller: "SICBundle:AdminAguasBlancas:show" }
    methods:  GET

configurables_tipos_aguas_blancas_new:
    path:     /new
    defaults: { _controller: "SICBundle:AdminAguasBlancas:new" }
    methods:  [GET, POST]

configurables_tipos_aguas_blancas_edit:
    path:     /{id}/edit
    defaults: { _controller: "SICBundle:AdminAguasBlancas:edit" }
    methods:  [GET, POST]

configurables_tipos_aguas_blancas_delete:
    path:     /{id}/delete
    defaults: { _controller: "SICBundle:AdminAguasBlancas:delete" }
    methods:  DELETE
