sic_usuarios:
    resource: "@SICBundle/Resources/config/routing/usuario.yml"
    prefix:   /usuarios

sic_rutas_extras:
    resource: "@SICBundle/Resources/config/routing/rutas_extras.yml"
    prefix:   /

sic_personas:
    resource: "@SICBundle/Resources/config/routing/persona.yml"
    prefix:   /personas

sic_comunidades:
    resource: "@SICBundle/Resources/config/routing/comunidad.yml"
    prefix:   /comunidades

sic_consejocomunal:
    resource: "@SICBundle/Resources/config/routing/consejocomunal.yml"
    prefix:   /consejocomunal

sic_grupofamiliar:
    resource: "@SICBundle/Resources/config/routing/grupofamiliar.yml"
    prefix:   /grupofamiliar

sic_jefegrupofamiliar:
    resource: "@SICBundle/Resources/config/routing/jefegrupofamiliar.yml"
    prefix:   /jefegrupofamiliar

sic_situacioneconomica:
    resource: "@SICBundle/Resources/config/routing/situacioneconomica.yml"
    prefix:   /situacioneconomica