sic_homepage:
    path:     /inicio
    defaults: { _controller: "SICBundle:Inicio:inicio" }
    methods:  GET

sic_usuarios:
    resource: "@SICBundle/Resources/config/routing/usuario.yml"
    prefix:   /usuarios

sic_personas:
    resource: "@SICBundle/Resources/config/routing/persona.yml"
    prefix:   /personas

sic_comunidades:
    resource: "@SICBundle/Resources/config/routing/comunidad.yml"
    prefix:   /comunidades

sic_consejocomunal:
    resource: "@SICBundle/Resources/config/routing/consejocomunal.yml"
    prefix:   /consejocomunal