sic_usuarios:
    resource: "@SICBundle/Resources/config/routing/usuario.yml"
    prefix:   /usuarios

sic_rutas_extras:
    resource: "@SICBundle/Resources/config/routing/rutas_extras.yml"
    prefix:   /

sic_personas:
    resource: "@SICBundle/Resources/config/routing/persona.yml"
    prefix:   /personas

sic_comunidades:
    resource: "@SICBundle/Resources/config/routing/comunidad.yml"
    prefix:   /comunidades

sic_consejocomunal:
    resource: "@SICBundle/Resources/config/routing/consejocomunal.yml"
    prefix:   /consejocomunal

sic_grupofamiliar:
    resource: "@SICBundle/Resources/config/routing/grupofamiliar.yml"
    prefix:   /grupofamiliar

sic_jefegrupofamiliar:
    resource: "@SICBundle/Resources/config/routing/jefegrupofamiliar.yml"
    prefix:   /jefegrupofamiliar

sic_situacioneconomica:
    resource: "@SICBundle/Resources/config/routing/situacioneconomica.yml"
    prefix:   /situacion/economica

sic_situacionvivienda:
    resource: "@SICBundle/Resources/config/routing/situacionvivienda.yml"
    prefix:   /situacion/vivienda

sic_situacionsalud:
    resource: "@SICBundle/Resources/config/routing/situacionsalud.yml"
    prefix:   /situacion/salud

sic_situacionservicios:
    resource: "@SICBundle/Resources/config/routing/situacionservicios.yml"
    prefix:   /situacion/servicios

sic_participacioncomunitaria:
    resource: "@SICBundle/Resources/config/routing/participacioncomunitaria.yml"
    prefix:   /participacioncomunitaria

sic_situacioncomunidad:
    resource: "@SICBundle/Resources/config/routing/situacioncomunidad.yml"
    prefix:   /situacion/comunidad

sic_planillas:
    resource: "@SICBundle/Resources/config/routing/planillas.yml"
    prefix:   /planillas

# ----------------------------------------------------------------------------

sic_admin_nacionalidad:
    resource: "@SICBundle/Resources/config/routing/Configurables/adminnacionalidad.yml"
    prefix:   /configurable/nacionalidad

sic_configurable_respuesta_cerrada:
    resource: "@SICBundle/Resources/config/routing/Configurables/adminrespcerrada.yml"
    prefix:   /configurable/respuesta/cerrada

sic_configurable_incapacidades:
    resource: "@SICBundle/Resources/config/routing/Configurables/adminincapacidades.yml"
    prefix:   /configurable/incapacidades

sic_configurable_pensionados_instituciones:
    resource: "@SICBundle/Resources/config/routing/Configurables/adminpensionadoinstitucion.yml"
    prefix:   /configurable/pensionados/instituciones

sic_configurable_estado_civil:
    resource: "@SICBundle/Resources/config/routing/Configurables/adminestadocivil.yml"
    prefix:   /configurable/estado_civil

sic_configurable_nivel_instruccion:
    resource: "@SICBundle/Resources/config/routing/Configurables/adminnivelinstruccion.yml"
    prefix:   /configurable/nivel_instruccion

sic_configurable_profesiones:
    resource: "@SICBundle/Resources/config/routing/Configurables/adminprofesion.yml"
    prefix:   /configurable/profesiones

sic_configurable_clasificacion_ingreso_familiar:
    resource: "@SICBundle/Resources/config/routing/Configurables/adminclasingresofamiliar.yml"
    prefix:   /configurable/clasificacion/ingreso_familiar

sic_configurable_ubicacion-trabajo:
    resource: "@SICBundle/Resources/config/routing/Configurables/adminubicaciontrabajo.yml"
    prefix:   /configurable/ubicacion-trabajo

sic_configurable_venta_vivenda:
    resource: "@SICBundle/Resources/config/routing/Configurables/adminventavivienda.yml"
    prefix:   /configurable/venta_vivenda

sic_configurable_tipos_ingresos:
    resource: "@SICBundle/Resources/config/routing/Configurables/admintipoingresos.yml"
    prefix:   /configurable/tipos/ingresos

sic_configurable_tipo_tenencia:
    resource: "@SICBundle/Resources/config/routing/Configurables/admintipotenencia.yml"
    prefix:   /configurable/tipo/tenencia

sic_configurable_tipo_vivienda:
    resource: "@SICBundle/Resources/config/routing/Configurables/admintipovivienda.yml"
    prefix:   /configurable/tipo/vivienda

sic_configurable_tipo_habitaciones:
    resource: "@SICBundle/Resources/config/routing/Configurables/admintipohabitacionesvivienda.yml"
    prefix:   /configurable/tipo/habitaciones

sic_configurable_tipo_paredes:
    resource: "@SICBundle/Resources/config/routing/Configurables/admintipoparedes.yml"
    prefix:   /configurable/tipo/paredes

sic_configurable_tipo_techo:
    resource: "@SICBundle/Resources/config/routing/Configurables/admintipotecho.yml"
    prefix:   /configurable/tipo/techo

sic_configurable_tipo_enseres:
    resource: "@SICBundle/Resources/config/routing/Configurables/admintipoenseres.yml"
    prefix:   /configurable/tipo/enseres

sic_configurable_tipo_salubridad:
    resource: "@SICBundle/Resources/config/routing/Configurables/adminsalubridadvivienda.yml"
    prefix:   /configurable/tipo/salubridad

sic_configurables_tipo_plagas:
    resource: "@SICBundle/Resources/config/routing/Configurables/admintipoplagas.yml"
    prefix:   /configurables/tipo/plagas

sic_configurable_tipo_mascotas:
    resource: "@SICBundle/Resources/config/routing/Configurables/admintipomascotas.yml"
    prefix:   /configurable/tipo/mascotas    