sic_usuarios:
    resource: "@SICBundle/Resources/config/routing/usuario.yml"
    prefix:   /usuarios

sic_rutas_extras:
    resource: "@SICBundle/Resources/config/routing/rutas_extras.yml"
    prefix:   /

sic_personas:
    resource: "@SICBundle/Resources/config/routing/persona.yml"
    prefix:   /miembro/grupo/familiar

sic_comunidades:
    resource: "@SICBundle/Resources/config/routing/comunidad.yml"
    prefix:   /comunidades

sic_consejocomunal:
    resource: "@SICBundle/Resources/config/routing/consejocomunal.yml"
    prefix:   /consejocomunal

sic_grupofamiliar:
    resource: "@SICBundle/Resources/config/routing/grupofamiliar.yml"
    prefix:   /grupofamiliar

sic_jefegrupofamiliar:
    resource: "@SICBundle/Resources/config/routing/jefegrupofamiliar.yml"
    prefix:   /jefegrupofamiliar

sic_situacioneconomica:
    resource: "@SICBundle/Resources/config/routing/situacioneconomica.yml"
    prefix:   /situacion/economica

sic_situacionvivienda:
    resource: "@SICBundle/Resources/config/routing/situacionvivienda.yml"
    prefix:   /situacion/vivienda

sic_situacionsalud:
    resource: "@SICBundle/Resources/config/routing/situacionsalud.yml"
    prefix:   /situacion/salud

sic_situacionservicios:
    resource: "@SICBundle/Resources/config/routing/situacionservicios.yml"
    prefix:   /situacion/servicios

sic_participacioncomunitaria:
    resource: "@SICBundle/Resources/config/routing/participacioncomunitaria.yml"
    prefix:   /participacion/comunitaria

sic_situacioncomunidad:
    resource: "@SICBundle/Resources/config/routing/situacioncomunidad.yml"
    prefix:   /situacion/comunidad

sic_planillas:
    resource: "@SICBundle/Resources/config/routing/planillas.yml"
    prefix:   /planillas

sic_noticia:
    resource: "@SICBundle/Resources/config/routing/noticia.yml"
    prefix:   /noticia

sic_bitacora:
    resource: "@SICBundle/Resources/config/routing/bitacora.yml"
    prefix:   /bitacora

sic_comunicado:
    resource: "@SICBundle/Resources/config/routing/comunicado.yml"
    prefix:   /comunicado

sic_comite:
    resource: "@SICBundle/Resources/config/routing/comite.yml"
    prefix:   /comites

sic_vocero:
    resource: "@SICBundle/Resources/config/routing/vocero.yml"
    prefix:   /voceros

# ----------------------------------------------------------------------------

sic_admin_nacionalidad:
    resource: "@SICBundle/Resources/config/routing/Configurables/adminnacionalidad.yml"
    prefix:   /administrar/configurables/nacionalidad

sic_configurable_respuesta_cerrada:
    resource: "@SICBundle/Resources/config/routing/Configurables/adminrespcerrada.yml"
    prefix:   /administrar/configurables/respuesta/cerrada

sic_configurable_incapacidades:
    resource: "@SICBundle/Resources/config/routing/Configurables/adminincapacidades.yml"
    prefix:   /administrar/configurables/incapacidades

sic_configurable_pensionados_instituciones:
    resource: "@SICBundle/Resources/config/routing/Configurables/adminpensionadoinstitucion.yml"
    prefix:   /administrar/configurables/pensionados/instituciones

sic_configurable_estado_civil:
    resource: "@SICBundle/Resources/config/routing/Configurables/adminestadocivil.yml"
    prefix:   /administrar/configurables/estado_civil

sic_configurable_nivel_instruccion:
    resource: "@SICBundle/Resources/config/routing/Configurables/adminnivelinstruccion.yml"
    prefix:   /administrar/configurables/nivel_instruccion

sic_configurable_profesiones:
    resource: "@SICBundle/Resources/config/routing/Configurables/adminprofesion.yml"
    prefix:   /administrar/configurables/profesiones

sic_configurable_clasificacion_ingreso_familiar:
    resource: "@SICBundle/Resources/config/routing/Configurables/adminclasingresofamiliar.yml"
    prefix:   /administrar/configurables/clasificacion/ingreso_familiar

sic_configurable_ubicacion-trabajo:
    resource: "@SICBundle/Resources/config/routing/Configurables/adminubicaciontrabajo.yml"
    prefix:   /administrar/configurables/ubicacion-trabajo

sic_configurable_venta_vivenda:
    resource: "@SICBundle/Resources/config/routing/Configurables/adminventavivienda.yml"
    prefix:   /administrar/configurables/venta_vivenda

sic_configurable_tipos_ingresos:
    resource: "@SICBundle/Resources/config/routing/Configurables/admintipoingresos.yml"
    prefix:   /administrar/configurables/tipos/ingresos

sic_configurable_tipo_tenencia:
    resource: "@SICBundle/Resources/config/routing/Configurables/admintipotenencia.yml"
    prefix:   /administrar/configurables/tipo/tenencia

sic_configurable_tipo_vivienda:
    resource: "@SICBundle/Resources/config/routing/Configurables/admintipovivienda.yml"
    prefix:   /administrar/configurables/tipo/vivienda

sic_configurable_tipo_habitaciones:
    resource: "@SICBundle/Resources/config/routing/Configurables/admintipohabitacionesvivienda.yml"
    prefix:   /administrar/configurables/tipo/habitaciones

sic_configurable_tipo_paredes:
    resource: "@SICBundle/Resources/config/routing/Configurables/admintipoparedes.yml"
    prefix:   /administrar/configurables/tipo/paredes

sic_configurable_tipo_techo:
    resource: "@SICBundle/Resources/config/routing/Configurables/admintipotecho.yml"
    prefix:   /administrar/configurables/tipo/techo

sic_configurable_tipo_enseres:
    resource: "@SICBundle/Resources/config/routing/Configurables/admintipoenseres.yml"
    prefix:   /administrar/configurables/tipo/enseres

sic_configurable_tipo_salubridad:
    resource: "@SICBundle/Resources/config/routing/Configurables/adminsalubridadvivienda.yml"
    prefix:   /administrar/configurables/tipo/salubridad

sic_configurables_tipo_plagas:
    resource: "@SICBundle/Resources/config/routing/Configurables/admintipoplagas.yml"
    prefix:   /administrar/configurables/tipo/plagas

sic_configurable_tipo_mascotas:
    resource: "@SICBundle/Resources/config/routing/Configurables/admintipomascotas.yml"
    prefix:   /administrar/configurables/tipo/mascotas

sic_configurable_tipo_padecencia:
    resource: "@SICBundle/Resources/config/routing/Configurables/admintipopadecencia.yml"
    prefix:   /administrar/configurables/tipo/padecencia

sic_configurable_tipo_ayuda_especial:
    resource: "@SICBundle/Resources/config/routing/Configurables/admintipoayudaespecial.yml"
    prefix:   /administrar/configurables/tipo/ayuda_especial

sic_configurable_tipo_situacion_exclusion:
    resource: "@SICBundle/Resources/config/routing/Configurables/admintiposituacionexclusion.yml"
    prefix:   /administrar/configurables/tipo/situacion_exclusion

sic_configurables_tipos_aguas_blancas:
    resource: "@SICBundle/Resources/config/routing/Configurables/adminaguasblancas.yml"
    prefix:   /administrar/configurables/tipos/aguas_blancas

sic_configurables_tipos_aguas_servidas:
    resource: "@SICBundle/Resources/config/routing/Configurables/adminaguasservidas.yml"
    prefix:   /administrar/configurables/tipos/aguas_servidas

sic_configurables_tipos_gas:
    resource: "@SICBundle/Resources/config/routing/Configurables/admintipogas.yml"
    prefix:   /administrar/configurables/tipos/gas

sic_configurables_tipo_sistema_electrico:
    resource: "@SICBundle/Resources/config/routing/Configurables/adminsistemaelectrico.yml"
    prefix:   /administrar/configurables/tipo/sistema_electrico

sic_configurables_tipo_recoleccion_basura:
    resource: "@SICBundle/Resources/config/routing/Configurables/adminrecoleccionbasura.yml"
    prefix:   /administrar/configurables/tipo/recoleccion_basura

sic_configurables_tipo_telefonia:
    resource: "@SICBundle/Resources/config/routing/Configurables/admintipotelefonia.yml"
    prefix:   /administrar/configurables/tipo/telefonia

sic_configurables_tipo_transporte:
    resource: "@SICBundle/Resources/config/routing/Configurables/admintipotransporte.yml"
    prefix:   /administrar/configurables/tipo/transporte

sic_configurables_tipo_mecanismo_informacion:
    resource: "@SICBundle/Resources/config/routing/Configurables/adminmecanismoinformacion.yml"
    prefix:   /administrar/configurables/tipo/mecanismo_informacion

sic_configurables_tipos_servicios_comunales:
    resource: "@SICBundle/Resources/config/routing/Configurables/adminservicioscomunales.yml"
    prefix:   /administrar/configurables/tipos/servicios_comunales

# --------------------------------------------------------------------

sic_configurables_tipos_organizaciones_comunitarias:
    resource: "@SICBundle/Resources/config/routing/Configurables/adminorgcomunitaria.yml"
    prefix:   /administrar/configurables/tipos/organizaciones/comunitarias

sic_configurables_tipos_misiones_comunidad:
    resource: "@SICBundle/Resources/config/routing/Configurables/adminmisionescomunidad.yml"
    prefix:   /administrar/configurables/tipos/misiones_comunidad

sic_configurables_preguntas_participacion_comunitaria:
    resource: "@SICBundle/Resources/config/routing/Configurables/adminpreguntasparticipacioncomunitaria.yml"
    prefix:   /administrar/configurables/preguntas/participacion_comunitaria

sic_configurables_tipos_areas_trabajo:
    resource: "@SICBundle/Resources/config/routing/Configurables/adminareatrabajocc.yml"
    prefix:   /administrar/configurables/tipos/areas_trabajo

sic_configurables_preguntas:
    resource: "@SICBundle/Resources/config/routing/Configurables/adminpreguntas.yml"
    prefix:   /administrar/configurables/preguntas